# Generated by Django 5.2.9 on 2026-01-06 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=30)),
                ('leave_reason', models.CharField(max_length=200)),
                ('leave_start_date', models.DateTimeField()),
                ('leave_end_date', models.DateTimeField()),
                ('leave_status', models.CharField(default='Pending', max_length=20, null=True)),
                ('leave_remark', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_leaverequest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
